.section .iram1, "ax"

.global context_switch
.type context_switch, @function

# a0 = current task descriptor
# a1 = next task descriptor

context_switch:

    # =========================================================
    # SAVE CURRENT CONTEXT
    # =========================================================

    addi sp, sp, -128

    sw ra,   0(sp)
    sw t0,   4(sp)
    sw t1,   8(sp)
    sw t2,  12(sp)

    sw s0,  16(sp)
    sw s1,  20(sp)

    sw a0,  24(sp)
    sw a1,  28(sp)
    sw a2,  32(sp)
    sw a3,  36(sp)
    sw a4,  40(sp)
    sw a5,  44(sp)
    sw a6,  48(sp)
    sw a7,  52(sp)

    sw s2,  56(sp)
    sw s3,  60(sp)
    sw s4,  64(sp)
    sw s5,  68(sp)
    sw s6,  72(sp)
    sw s7,  76(sp)
    sw s8,  80(sp)
    sw s9,  84(sp)
    sw s10, 88(sp)
    sw s11, 92(sp)

    sw t3,  96(sp)
    sw t4, 100(sp)
    sw t5, 104(sp)
    sw t6, 108(sp)

    csrr t0, mstatus
    sw t0, 112(sp)

    csrr t0, mepc
    sw t0, 116(sp)

    sw gp, 120(sp)
    sw tp, 124(sp)

    # save current SP into current task->P
    sw sp, 0(a0)


    ca

    # =========================================================
    # RESTORE NEXT CONTEXT
    # =========================================================

    # load next task SP
    lw sp, 0(a0)

    lw ra,   0(sp)
    lw t0,   4(sp)
    lw t1,   8(sp)
    lw t2,  12(sp)

    lw s0,  16(sp)
    lw s1,  20(sp)

    lw a0,  24(sp)
    lw a1,  28(sp)
    lw a2,  32(sp)
    lw a3,  36(sp)
    lw a4,  40(sp)
    lw a5,  44(sp)
    lw a6,  48(sp)
    lw a7,  52(sp)

    lw s2,  56(sp)
    lw s3,  60(sp)
    lw s4,  64(sp)
    lw s5,  68(sp)
    lw s6,  72(sp)
    lw s7,  76(sp)
    lw s8,  80(sp)
    lw s9,  84(sp)
    lw s10, 88(sp)
    lw s11, 92(sp)

    lw t3,  96(sp)
    lw t4, 100(sp)
    lw t5, 104(sp)
    lw t6, 108(sp)

    lw t0, 112(sp)
    csrw mstatus, t0

    lw t0, 116(sp)
    csrw mepc, t0

    lw gp, 120(sp)
    lw tp, 124(sp)

    addi sp, sp, 128

    mret